name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ${{ matrix.os-image }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    strategy:
      fail-fast: false

      matrix:
        include:
          # Linux GCC
          - name: "Ubuntu 24.04: GCC-14"
            os: linux
            os-image: ubuntu-24.04
            cc: "gcc-14"
            cxx: "g++-14"

          - name: "Ubuntu 26.04: GCC-15"
            os: linux
            os-image: ubuntu-26.04
            cc: "gcc-15"
            cxx: "g++-15"

          - name: "Ubuntu 24.04 ARM: GCC-14"
            os: linux
            os-image: ubuntu-24.04-arm
            cc: "gcc-14"
            cxx: "g++-14"

          - name: "Ubuntu 26.04 ARM: GCC-15"
            os: linux
            os-image: ubuntu-26.04-arm
            cc: "gcc-15"
            cxx: "g++-15"

          # Linux Clang
          - name: "Ubuntu 24.04: Clang-18"
            os: linux
            os-image: ubuntu-24.04
            cc: "clang-18"
            cxx: "clang++-18"

          - name: "Ubuntu 26.04: Clang-22"
            os: linux
            os-image: ubuntu-26.04
            cc: "clang-22"
            cxx: "clang++-22"

          - name: "Ubuntu 24.04 ARM: Clang-18"
            os: linux
            os-image: ubuntu-24.04-arm
            cc: "clang-18"
            cxx: "clang++-18"

          - name: "Ubuntu 26.04 ARM: Clang-22"
            os: linux
            os-image: ubuntu-26.04-arm
            cc: "clang-22"
            cxx: "clang++-22"

          # Windows MSVC
          - name: "Windows: MSVC"
            os: windows
            os-image: windows-latest
            cc: "cl"
            cxx: "cl"

          # MacOS Clang
          - name: "MacOS 26: Clang"
            os: macos
            os-image: macos-26
            cc: clang
            cxx: clang++
            cmake-flags: -DSTRING_ENUM_CXX_MODULES=Off

    steps:
    - uses: actions/checkout@v7

    - name: Prepare environment (Windows)
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows'

    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: cmake --preset debug ${{ matrix.cmake-flags }}

    - name: Build
      working-directory: ${{ github.workspace }}
      run: cmake --build --preset debug

    - name: Test
      working-directory: ${{ github.workspace }}
      run: ctest --preset debug
